### ISSUE TITLE
Phaser 3 Branch, incorrect instructions

### ISSUE THREAD

**Issue by micheg** [kaiostech/phaser-sample-app#1]
The instructions in the readme of the phaser 3 branch are incorrect.
To clone the version with phaser 3 you need to do:
git clone -b  phaser3 https://github.com/kaiostech/phaser-sample-app.git

**Comment by wulaiyin789** [comment]
Thanks for the correction, @micheg.

The issue fixed in [here](https://github.com/kaiostech/phaser-sample-app/commit/0772cdade8751f9dd15787fb86177e043b2dcd7f)
